# Generated by Django 4.1.2 on 2022-10-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_goodcard_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodcard',
            options={'ordering': ['title'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='goodcategory',
            options={'ordering': ['title'], 'verbose_name': 'Категория товаров', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterField(
            model_name='goodcard',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
